### ISSUE TITLE
Memory use for big models

### ISSUE THREAD

**Issue by thsmit** [topopt/TopOpt_in_PETSc#11]
Hi, 

When I am testing the standard problem with large meshes: 4 to 40 million elements, I see that the memory requirements go up into more than a 100GB's. For these testes I used between 16 and 48 cores and a density filter with a very small filter radius.

Is this memory usage normal or is there a way to decrease the amount of memory required?

Best, Thijs

**Comment by topopt** [comment]
From petsc 3.11 and on you can use the following run time command to reduce memory use in the Galerkin projection: -matptap_via allatonce_merged
