### ISSUE TITLE
TopOpt.h:4:10: fatal error: petsc.h:No such file or directory

### ISSUE THREAD

**Issue by aiwanzhe** [topopt/TopOpt_in_PETSc#17]
I can't make TopOpt successfully. When I do make TopOpt, it says "TopOpt.h:4:10: fatal error: petsc.h:No such file or directory". Could you please tell me how to do with it?

**Comment by dakota-bit-uav4** [comment]
I haven't use that code anymore, maybe you can try the topopt in 99 lines and 88 lines in MATLAB instead



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "topopt/TopOpt_in_PETSc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 上午9:58
收件人:&nbsp;"topopt/TopOpt_in_PETSc"<TopOpt_in_PETSc@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[topopt/TopOpt_in_PETSc] TopOpt.h:4:10: fatal error: petsc.h:No such file or directory (#17)





 
I can't make TopOpt successfully. When I do make TopOpt, it says "TopOpt.h:4:10: fatal error: petsc.h:No such file or directory". Could you please tell me how to do with it?
