### ISSUE TITLE
Question of Update() paramters

### ISSUE THREAD

**Issue by Fabian188** [topopt/TopOpt_in_PETSc#21]
Update has the following header

`Update(Vec xval, Vec dfdx, PetscScalar* gx, Vec* dgdx, Vec xmin, Vec xmax);`

I do not see, how the objective value fx enters the problem. Svanberg combines objective and constraints to a m+1 vector. But in Update() we have the derivative of the objective, the constraints values and the constraints gradient. 

I assume, the value is skipped, as it has no impact on the sub-problem solution and we have no globalization here. As this is different to the '87 Svanberg paper I suggest to at least comment.

**Comment by topopt** [comment]
Hi Fabian,

You are absolutely right - the objective is not used for the standard MMA problem solvers. Nor are they used in Kristers matlab/fortran implementations. He just passes them anyway. I have added a reference to the correct paper in the header for the mma source code.

Best wishes
Niels
