### ISSUE TITLE
LinearElasticity.cc error 

### ISSUE THREAD

**Issue by thanhchuong8252** [topopt/TopOpt_in_PETSc#6]
Dear all,

are there anyone have the problem when run make topopt with the error like this?, can you help me to see the problem.

/Documents/TopOpt_in_PETSc/LinearElasticity.cc:613:32: error: cannot convert ‘PetscBool’ to ‘PCMGGalerkinType’ for argument ‘2’ to ‘PetscErrorCode PCMGSetGalerkin(PC, PCMGGalerkinType)’
   PCMGSetGalerkin(pc,PETSC_TRUE);

**Comment by topopt** [comment]
Thanks for bringing the problem to our attention. The issues associated with PETSC version 3.8.3 have now been resolved.

NAA

**Comment by thanhchuong8252** [comment]
thank you very much, best regards
