### ISSUE TITLE
Problem with plotting

### ISSUE THREAD

**Issue by rveltz** [topopt/TopOpt_in_PETSc#7]
Dear all,

I am trying to reproduce the example. I ran:

`mpiexec -np 4 ./topopt -filter 2 -rmin 0.2 -volfrac 0.3 -maxItr 160`

then

`python bin2vtu.py 18`.

However, when opening the file `output_00018.vtu`, I get an empty box:

<img width="1555" alt="screen shot 2018-02-22 at 09 43 23" src="https://user-images.githubusercontent.com/1591812/36528300-e0a6afea-17b4-11e8-8040-f9cf573b4860.png">

Can you give me a hint please?

THank you for your help,

Romain

**Comment by topopt** [comment]
Hi Romain,

It looks as if you are using "point" visualization and not "surface" which is better. And then you need to select the field you want to inspect, i.e. the design "xPhys" or the displacements "ux, uy, uz".

Hope this helps
Niels
